### ISSUE TITLE
Stackdriver not parsing Python print statement as jsonPayload

### ISSUE THREAD

**Issue by mitchellsuter** [googleapis/python-functions#10]
When trying to create a structured log in a Python Cloud Function, Stackdriver is not parsing as jsonPayload but as textPayload.

Use the provided example to see:
https://cloud.google.com/functions/docs/monitoring/logging#writing_structured_logs

**Comment by grayside** [comment]
Hi @mitchellsuter, thank you for the bug report.

I've verified the sample works with Python 3.8 but does not work in Python 3.7.

For your Python 3.7 functions, you should use plain strings or the client library. You might also consider upgrading to Python 3.8.

If you are using Python 3.8 and you are encountering this problem, please reopen the issue with further details.

**Comment by mitchellsuter** [comment]
@grayside Confirming that upgrading to Python 3.8 works.
