### ISSUE TITLE
Where do I find examples of create_function with real integration

### ISSUE THREAD

**Issue by shobsi** [googleapis/python-functions#249]
I am trying to create cloud functions from python code by following 

https://cloud.google.com/python/docs/reference/cloudfunctions/latest/google.cloud.functions_v2.services.function_service.FunctionServiceClient#google_cloud_functions_v2_services_function_service_FunctionServiceClient_create_function

I found the source code at

https://github.com/googleapis/python-functions/blob/8fa10be9991622bfba4a5f974917281ff79bd04e/google/cloud/functions_v2/services/function_service/transports/grpc.py#L310

And some tests with mocked create_function at 

https://github.com/googleapis/python-functions/blob/main/tests/unit/gapic/functions_v2/test_function_service.py

I am looking for examples where a cloud function is created for real using python APIs. Is there a place where I can find it?

**Comment by parthea** [comment]
I was unable to transfer this issue. I've requested sample code via https://github.com/GoogleCloudPlatform/python-docs-samples/issues/9129.
