### ISSUE TITLE
Memory issues in a Cloud Storage Function

### ISSUE THREAD

**Issue by MishalJasmine** [googleapis/python-functions#97]
TI have deployed a storage trigger cloud function that needs more memory. While deploying the GCF, I have deployed in the following manner with the appropriate flags.

    gcloud functions deploy GCF_name--runtime python37 --trigger-resource bucket_name --trigger-event google.storage.object.finalize --timeout 540s --memory 8192MB

But I observed in the google cloud console, the memory utilization map is not going beyond 2GB. And in the logs I am getting this error,
  
    Function execution took 34566 ms, finished with status: 'connection error' .

which happens because of memory shortage. Can I get some help on this.

**Comment by MishalJasmine** [comment]
![image](https://user-images.githubusercontent.com/51846137/129713645-410e315f-060b-4f6d-b70b-1ebce99b6f0e.png)

**Comment by ace-n** [comment]
@squee1945 PTAL?

**Comment by squee1945** [comment]
Is it possible to construct a reproduction? There's not enough for us to go on.

**Comment by engelke** [comment]
Support ticket (if filed) investigation will analyze this issue and file bugs if needed.
